FROM java:8
VOLUME /tmp
COPY target/Fizzbuzz-1.0-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 1221


# docker build -f Dockerfile -t fizzbuzz_img .
# docker run -d --name fizzbuzz -p 8181:1221 fizzbuzz_img