FROM java:8
VOLUME /tmp
COPY target/Fizzbuzz-1.0-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
EXPOSE 8181


# docker build -f Dockerfile -t fizzbuzz_img .
# docker run -d --name fizzbuzz -p 8181:8181 fizzbuzz_img